; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

board_build.flash_mode = qio
board_build.flash_freq = 80m
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB

src_filter = +<*> -<.git/> -<.pio/> -<test/> +<../screens/> +<../fonts/>

build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DUSER_SETUP_LOADED=1
    -DGC9A01_DRIVER=1
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=240
    -DTFT_CS=13
    -DTFT_MOSI=8
    -DTFT_SCLK=9
    -DTFT_MISO=-1
    -DTFT_DC=14
    -DTFT_RST=21
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DLOAD_FONT4=1
    -DLOAD_FONT6=1
    -DLOAD_FONT7=1
    -DLOAD_FONT8=1
    -DLOAD_GFXFF=1
    -DSMOOTH_FONT=1
    -DUSE_FSPI_PORT=1
    -DSPI_FREQUENCY=80000000
    -Wno-error=narrowing
    -DLOG_LOCAL_LEVEL=ESP_LOG_WARN

lib_deps = 
    adafruit/Adafruit NeoPixel @ ^1.12.0
    bodmer/TFT_eSPI @ ^2.5.43
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    lvgl/lvgl @ ^9.2.2